#!/bin/sh

whelp() {
        echo "DBus based power and session management command"
        echo "Usage: wshutdown [option]"
        echo " --help      show this help"
        echo " -s          suspend"
        echo " -h          hibernate"
        echo " -e          logout"
        echo " -r          reboot"
        echo " -l          lock screen"
        echo " [no arg]    shutdown"
}

_dbus_send="dbus-send --system --print-reply \
--dest=org.freedesktop.ConsoleKit \
/org/freedesktop/ConsoleKit/Manager \
org.freedesktop.ConsoleKit.Manager"


case "$1" in
    --help)
        whelp
        ;;
    -s)
        ${_dbus_send}.Suspend
        ;;
    -h)
        ${_dbus_send}.Hibernate
        ;;
    -l)
        if command -v swaylock >/dev/null 2>&1; then
            swaylock -f -c 000000
        fi
        ;;
    -e)
        wlrctl toplevel close
        sleep 1
        [ "$XDG_CURRENT_DESKTOP" = "labwc" ] && labwc -e
        ;;
    -r)
        wlrctl toplevel close
        sleep 1
        ${_dbus_send}.Restart
        ;;
    "")
        wlrctl toplevel close
        sleep 1
        ${_dbus_send}.Stop
        ;;
    *)
        whelp
        exit 1
        ;;
esac

exit
